name: ishla
description: "A new Flutter project for finding job for users and posting jobs"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # firebase stuff
  firebase_core: ^3.12.1
  # internet service
  dio: ^5.7.0
  # svg
  flutter_svg: ^2.0.10+1
  #  # lottie animation
  #  lottie: ^3.1.3
  # screen responsibility
  flutter_screenutil: ^5.9.3
  # logs
  l: ^4.0.2
  # to check on other devices
  device_preview: ^1.2.0
  # state management
  get: ^4.6.6
  # for app storage
  shared_preferences: ^2.3.2
  # google sign in
  google_sign_in: ^6.2.2
  # cloud firestore
  cloud_firestore: ^5.5.0
  # to check connectivity
  connectivity_plus: ^6.1.0
  flutter_animate: ^4.5.2
  google_maps_flutter: ^2.12.1
  url_launcher: ^6.3.1
  intl: ^0.19.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 23
  remove_alpha_ios: true